# Example configuration for the evaluation script
model: "meta-llama/llama-3.3-70b-instruct"
provider: "Hyperbolic"
output_dir: "results"
max_concurrent: 10

categories:
  - category: "algorithmic"
    datasets:
      - dataset: "binary_matrix"
        size: 50
        seed: 42
        params:
          min_size: 3
          max_size: 5

      - dataset: "caesar_cipher"
        size: 30
        seed: 123

      - dataset: "word_ladder"
        size: 40
        seed: 456
        params:
          min_word_length: 4
          max_word_length: 6

  - category: "arithmetic"
    datasets:
      - dataset: "chain_sum"
        size: 100
        seed: 789
        params:
          min_terms: 2
          max_terms: 5
          min_digits: 1
          max_digits: 3

      - dataset: "basic_arithmetic"
        size: 30
        seed: 101
